### ISSUE TITLE
Disappearing cover

### ISSUE THREAD

**Issue by zikalify** [standardebooks/jane-addams_twenty-years-at-hull-house#1]
The cover of the compatible epub version vanishes when importing the book into Calibre and Google Play Books.

**Comment by acabal** [comment]
This might be because of the ebook file size; I've converted some PNGs to JPG to save a few MB. But there are still a lot of illustrations, so if that doesn't work you should file a bug there instead.

**Comment by zikalify** [comment]
I've redownloaded the book since it was resized but still got a plain black front cover.

'so if that doesn't work you should file a bug there instead', where?

**Comment by acabal** [comment]
Actually, on closer inspection it does seem to be a different error in the ebook. I've gone ahead and fixed it, so it should hopefully work now. Wait an hour before downloading the new version from our website as the server will take quite some time to build it.

**Comment by zikalify** [comment]
Yes, it's working now, thanks.
